# Generated by Django 3.0.6 on 2020-08-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='multi_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variant',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
