# Generated by Django 3.0.6 on 2020-08-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200812_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
